# Generated by Django 4.2.1 on 2023-07-03 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('date1', models.DateField()),
                ('date2', models.DateField(blank=True, null=True)),
                ('date3', models.DateField(blank=True, null=True)),
                ('date4', models.DateField(blank=True, null=True)),
                ('course1', models.TextField()),
                ('course2', models.TextField(blank=True, null=True)),
                ('course3', models.TextField(blank=True, null=True)),
                ('course4', models.TextField(blank=True, null=True)),
                ('organizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizer', to=settings.AUTH_USER_MODEL)),
                ('players', models.ManyToManyField(blank=True, null=True, related_name='players', through='tourney_time.Player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField(default=1)),
                ('hole1', models.IntegerField(blank=True, default=0)),
                ('hole2', models.IntegerField(blank=True, default=0)),
                ('hole3', models.IntegerField(blank=True, default=0)),
                ('hole4', models.IntegerField(blank=True, default=0)),
                ('hole5', models.IntegerField(blank=True, default=0)),
                ('hole6', models.IntegerField(blank=True, default=0)),
                ('hole7', models.IntegerField(blank=True, default=0)),
                ('hole8', models.IntegerField(blank=True, default=0)),
                ('hole9', models.IntegerField(blank=True, default=0)),
                ('hole10', models.IntegerField(blank=True, default=0)),
                ('hole11', models.IntegerField(blank=True, default=0)),
                ('hole12', models.IntegerField(blank=True, default=0)),
                ('hole13', models.IntegerField(blank=True, default=0)),
                ('hole14', models.IntegerField(blank=True, default=0)),
                ('hole15', models.IntegerField(blank=True, default=0)),
                ('hole16', models.IntegerField(blank=True, default=0)),
                ('hole17', models.IntegerField(blank=True, default=0)),
                ('hole18', models.IntegerField(blank=True, default=0)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='tourney_time.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourney_time.tournament'),
        ),
    ]
